using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraMovement : MonoBehaviour
{
	public Transform target;
	public float Smoothing;
	public Vector2 MaxCameraPosition;
	public Vector2 MinCameraPosition;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void LateUpdate()
    {
		Vector3 targetPosition = new Vector3 (target.position.x, target.position.y, transform.position.z);

		targetPosition.x = Mathf.Clamp(targetPosition.x, MinCameraPosition.x, MaxCameraPosition.x);
		targetPosition.y = Mathf.Clamp(targetPosition.y, MinCameraPosition.y, MaxCameraPosition.y);

		if(transform.position != target.position) {
			
			transform.position = Vector3.Lerp(transform.position, targetPosition, Smoothing );
		}
    }
}
